language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - "pip install unittest2"
  - "pip install -r requirements.txt"
script: python tests.py
